/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE TRAJ_LOAD_SD_CARD PACKING
package com.MAVLink.pscom;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Load trajectory file from SD card.
 */
public class msg_traj_load_sd_card extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_TRAJ_LOAD_SD_CARD = 51809;
    public static final int MAVLINK_MSG_LENGTH = 63;
    private static final long serialVersionUID = MAVLINK_MSG_ID_TRAJ_LOAD_SD_CARD;

    
    /**
     * Name of file
     */
    @Description("Name of file")
    @Units("")
    public byte filename[] = new byte[63];
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_TRAJ_LOAD_SD_CARD;

        
        for (int i = 0; i < filename.length; i++) {
            packet.payload.putByte(filename[i]);
        }
                    
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a traj_load_sd_card message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        
        for (int i = 0; i < this.filename.length; i++) {
            this.filename[i] = payload.getByte();
        }
                
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_traj_load_sd_card() {
        this.msgid = MAVLINK_MSG_ID_TRAJ_LOAD_SD_CARD;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_traj_load_sd_card( byte[] filename) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_LOAD_SD_CARD;

        this.filename = filename;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_traj_load_sd_card( byte[] filename, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_LOAD_SD_CARD;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.filename = filename;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_traj_load_sd_card(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_LOAD_SD_CARD;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

     
    /**
    * Sets the buffer of this message with a string, adds the necessary padding
    */
    public void setFilename(String str) {
        int len = Math.min(str.length(), 63);
        for (int i=0; i<len; i++) {
            filename[i] = (byte) str.charAt(i);
        }

        for (int i=len; i<63; i++) {            // padding for the rest of the buffer
            filename[i] = 0;
        }
    }

    /**
    * Gets the message, formatted as a string
    */
    public String getFilename() {
        StringBuffer buf = new StringBuffer();
        for (int i = 0; i < 63; i++) {
            if (filename[i] != 0)
                buf.append((char) filename[i]);
            else
                break;
        }
        return buf.toString();

    }
                         
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_TRAJ_LOAD_SD_CARD - sysid:"+sysid+" compid:"+compid+" filename:"+filename+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_TRAJ_LOAD_SD_CARD";
    }
}
        