/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE TRAJ_K2 PACKING
package com.MAVLink.pscom;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Send second half of a gain matrix
 */
public class msg_traj_k2 extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_TRAJ_K2 = 51814;
    public static final int MAVLINK_MSG_LENGTH = 242;
    private static final long serialVersionUID = MAVLINK_MSG_ID_TRAJ_K2;

    
    /**
     * Second half of gain matrix
     */
    @Description("Second half of gain matrix")
    @Units("")
    public float K2[] = new float[60];
    
    /**
     * Index of gain matrix
     */
    @Description("Index of gain matrix")
    @Units("")
    public int k;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_TRAJ_K2;

        
        for (int i = 0; i < K2.length; i++) {
            packet.payload.putFloat(K2[i]);
        }
                    
        packet.payload.putUnsignedShort(k);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a traj_k2 message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        
        for (int i = 0; i < this.K2.length; i++) {
            this.K2[i] = payload.getFloat();
        }
                
        this.k = payload.getUnsignedShort();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_traj_k2() {
        this.msgid = MAVLINK_MSG_ID_TRAJ_K2;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_traj_k2( float[] K2, int k) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_K2;

        this.K2 = K2;
        this.k = k;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_traj_k2( float[] K2, int k, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_K2;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.K2 = K2;
        this.k = k;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_traj_k2(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_K2;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_TRAJ_K2 - sysid:"+sysid+" compid:"+compid+" K2:"+K2+" k:"+k+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_TRAJ_K2";
    }
}
        