/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE TRAJ_INFO PACKING
package com.MAVLink.pscom;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Start a trajectory upload. NOTE: GAIN MATRIX K[0] SHOULD ALWAYS BE THE HOVER MATRIX.
 */
public class msg_traj_info extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_TRAJ_INFO = 51810;
    public static final int MAVLINK_MSG_LENGTH = 10;
    private static final long serialVersionUID = MAVLINK_MSG_ID_TRAJ_INFO;

    
    /**
     * # Trajectory points
     */
    @Description("# Trajectory points")
    @Units("")
    public long n;
    
    /**
     * # Gain matrices
     */
    @Description("# Gain matrices")
    @Units("")
    public int k;
    
    /**
     * Gain matrix dim1
     */
    @Description("Gain matrix dim1")
    @Units("")
    public int k_dim1;
    
    /**
     * Gain matrix dim2
     */
    @Description("Gain matrix dim2")
    @Units("")
    public int k_dim2;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_TRAJ_INFO;

        packet.payload.putUnsignedInt(n);
        packet.payload.putUnsignedShort(k);
        packet.payload.putUnsignedShort(k_dim1);
        packet.payload.putUnsignedShort(k_dim2);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a traj_info message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.n = payload.getUnsignedInt();
        this.k = payload.getUnsignedShort();
        this.k_dim1 = payload.getUnsignedShort();
        this.k_dim2 = payload.getUnsignedShort();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_traj_info() {
        this.msgid = MAVLINK_MSG_ID_TRAJ_INFO;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_traj_info( long n, int k, int k_dim1, int k_dim2) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_INFO;

        this.n = n;
        this.k = k;
        this.k_dim1 = k_dim1;
        this.k_dim2 = k_dim2;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_traj_info( long n, int k, int k_dim1, int k_dim2, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_INFO;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.n = n;
        this.k = k;
        this.k_dim1 = k_dim1;
        this.k_dim2 = k_dim2;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_traj_info(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_INFO;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

            
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_TRAJ_INFO - sysid:"+sysid+" compid:"+compid+" n:"+n+" k:"+k+" k_dim1:"+k_dim1+" k_dim2:"+k_dim2+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_TRAJ_INFO";
    }
}
        