/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE TRAJ_REQ_K2 PACKING
package com.MAVLink.pscom;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Request the second half of a gain matrix.
 */
public class msg_traj_req_k2 extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_TRAJ_REQ_K2 = 51813;
    public static final int MAVLINK_MSG_LENGTH = 2;
    private static final long serialVersionUID = MAVLINK_MSG_ID_TRAJ_REQ_K2;

    
    /**
     * Index of gain matrix
     */
    @Description("Index of gain matrix")
    @Units("")
    public int k;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_TRAJ_REQ_K2;

        packet.payload.putUnsignedShort(k);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a traj_req_k2 message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.k = payload.getUnsignedShort();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_traj_req_k2() {
        this.msgid = MAVLINK_MSG_ID_TRAJ_REQ_K2;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_traj_req_k2( int k) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_REQ_K2;

        this.k = k;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_traj_req_k2( int k, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_REQ_K2;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.k = k;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_traj_req_k2(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_REQ_K2;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

      
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_TRAJ_REQ_K2 - sysid:"+sysid+" compid:"+compid+" k:"+k+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_TRAJ_REQ_K2";
    }
}
        