/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE TRAJ_ACK PACKING
package com.MAVLink.pscom;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Send a response regarding whether the trajectory load was successful.
 */
public class msg_traj_ack extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_TRAJ_ACK = 51820;
    public static final int MAVLINK_MSG_LENGTH = 5;
    private static final long serialVersionUID = MAVLINK_MSG_ID_TRAJ_ACK;

    
    /**
     * Number of points successfully loaded (-1 if error).
     */
    @Description("Number of points successfully loaded (-1 if error).")
    @Units("")
    public long points_loaded;
    
    /**
     * Result of load.
     */
    @Description("Result of load.")
    @Units("")
    public short result;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_TRAJ_ACK;

        packet.payload.putUnsignedInt(points_loaded);
        packet.payload.putUnsignedByte(result);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a traj_ack message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.points_loaded = payload.getUnsignedInt();
        this.result = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_traj_ack() {
        this.msgid = MAVLINK_MSG_ID_TRAJ_ACK;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_traj_ack( long points_loaded, short result) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_ACK;

        this.points_loaded = points_loaded;
        this.result = result;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_traj_ack( long points_loaded, short result, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_ACK;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.points_loaded = points_loaded;
        this.result = result;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_traj_ack(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_ACK;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_TRAJ_ACK - sysid:"+sysid+" compid:"+compid+" points_loaded:"+points_loaded+" result:"+result+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_TRAJ_ACK";
    }
}
        