/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE TRAJ_PT PACKING
package com.MAVLink.pscom;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Send a trajectory point.
 */
public class msg_traj_pt extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_TRAJ_PT = 51816;
    public static final int MAVLINK_MSG_LENGTH = 72;
    private static final long serialVersionUID = MAVLINK_MSG_ID_TRAJ_PT;

    
    /**
     * Index of trajectory point
     */
    @Description("Index of trajectory point")
    @Units("")
    public long k;
    
    /**
     * State trajectory vector
     */
    @Description("State trajectory vector")
    @Units("")
    public float x[] = new float[12];
    
    /**
     * Reference input vector
     */
    @Description("Reference input vector")
    @Units("")
    public float uref[] = new float[4];
    
    /**
     * Time
     */
    @Description("Time")
    @Units("")
    public float time;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_TRAJ_PT;

        packet.payload.putUnsignedInt(k);
        
        for (int i = 0; i < x.length; i++) {
            packet.payload.putFloat(x[i]);
        }
                    
        
        for (int i = 0; i < uref.length; i++) {
            packet.payload.putFloat(uref[i]);
        }
                    
        packet.payload.putFloat(time);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a traj_pt message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.k = payload.getUnsignedInt();
        
        for (int i = 0; i < this.x.length; i++) {
            this.x[i] = payload.getFloat();
        }
                
        
        for (int i = 0; i < this.uref.length; i++) {
            this.uref[i] = payload.getFloat();
        }
                
        this.time = payload.getFloat();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_traj_pt() {
        this.msgid = MAVLINK_MSG_ID_TRAJ_PT;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_traj_pt( long k, float[] x, float[] uref, float time) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_PT;

        this.k = k;
        this.x = x;
        this.uref = uref;
        this.time = time;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_traj_pt( long k, float[] x, float[] uref, float time, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_PT;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.k = k;
        this.x = x;
        this.uref = uref;
        this.time = time;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_traj_pt(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_TRAJ_PT;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

            
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_TRAJ_PT - sysid:"+sysid+" compid:"+compid+" k:"+k+" x:"+x+" uref:"+uref+" time:"+time+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_TRAJ_PT";
    }
}
        